name: Formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install packages
        working-directory: documentation
        run: |
             pip install black==24.8.0
      - name: Check formatting
        run: |
             black --check .
