name: dox_style Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python: [3.9, 3.11, 3.12]
        include:
          - os: macos
            python: "3.10"
          - os: windows
            python: 3.12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install packages
        working-directory: documentation
        run: |
             pip install -r requirements.txt
      - name: Run unit tests
        working-directory: dox_style
        run: |
             python -m unittest
